### ISSUE TITLE
-3500 Sign-on Restriction Error

### ISSUE THREAD

**Issue by TheShowstopper** [MrTimscampi/plugin.video.wwenetwork#1]
Half the time after telling me I've signed in successfully, it now tells me this:

![image](https://cloud.githubusercontent.com/assets/12618177/7870358/a90ae02c-0580-11e5-810e-36a81c4daa7d.png)

The other half of the time, it logs me in fine but then does nothing when I click anything.

**Comment by MrTimscampi** [comment]
This error comes from the video authentication.
There are two authentication: the login of your account and the authorisation of the video.

The video authentication has an automatic temporary "ban" if you spam it.
For now, it's done at the same time as login for the live stream. This is going to change (In fact, I'm working on that, right now, as it's preventing me from reliably listing all RAWs) and it should be less of a problem.
However, I can't eliminate it completely, as it's a server-side thing.

The next commit should solve this issue, so I'll close it when I commit and we'll see how it goes.
